name: Release Ubuntu

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: master
          fetch-depth: 0
          fetch-tags: true

      - name: Set jadx version
        id: setversion
        run: |
          echo "JADX_VERSION=$(git describe)" >> $GITHUB_ENV

      # Uses:
      # - Ubuntu 24.04 OOTB JDK (Temurin, already installed)
      # - Gradle Wrapper from repo
      - name: Build cross-platform distribution
        run: ./gradlew --no-daemon dist

      - name: Verify artifacts
        run: |
          ls -l build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.JADX_VERSION }}
          draft: false
          fail_on_unmatched_files: true
          files: build/*.zip
          tag_name: ${{ env.JADX_VERSION }}
